spring:
  application:
    name: TAXIE-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/rbathineni/git-local-cloud-config
          searchPaths: ${ENV_MODE}
          
          #username: trolley
          #password: strongpassword
          #skipSslValidation: true
          #timeout: 4
server:
  port: 8888
